const swaggerJsdoc = require('swagger-jsdoc');

const options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'INGENZI HRMS API',
      version: '1.0.0',
      description: 'Human Resource Management System API Documentation',
      contact: {
        name: 'INGENZI',
        email: 'info@ingenzi.com',
        url: 'https://ingenzi.com/'
      },
      license: {
        name: 'ISC',
        url: 'https://opensource.org/licenses/ISC'
      }
    },
    servers: [
      {
        url: process.env.API_BASE_URL || `http://localhost:${process.env.PORT || 3001}`,
        description: 'Development server'
      },
      {
        url: 'https://api.ingenzi.com',
        description: 'Production server'
      }
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
          description: 'Enter JWT token'
        }
      },
      schemas: {
        User: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            email: { type: 'string', format: 'email' },
            name: { type: 'string' },
            role: { type: 'string', enum: ['employee', 'hr_manager', 'system_admin'] },
            employeeId: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Employee: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            employeeId: { type: 'string' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string', nullable: true },
            departmentId: { type: 'integer' },
            position: { type: 'string' },
            salary: { type: 'number', format: 'decimal' },
            hireDate: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['active', 'inactive', 'terminated'] },
            address: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Department: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            name: { type: 'string' },
            description: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['active', 'inactive'] },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        LeaveRequest: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            employeeId: { type: 'integer', readOnly: true, description: 'Auto-set from logged-in user' },
            leaveTypeId: { type: 'integer' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            days: { type: 'integer', readOnly: true, description: 'Auto-calculated from dates' },
            reason: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['pending', 'approved', 'rejected'], readOnly: true, description: 'Defaults to pending' },
            appliedDate: { type: 'string', format: 'date-time', readOnly: true },
            approvedBy: { type: 'integer', nullable: true, readOnly: true },
            approvedDate: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
            comments: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Attendance: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            employeeId: { type: 'integer' },
            date: { type: 'string', format: 'date' },
            checkIn: { type: 'string', format: 'date-time', nullable: true },
            checkOut: { type: 'string', format: 'date-time', nullable: true },
            hoursWorked: { type: 'number', format: 'decimal', nullable: true, readOnly: true, description: 'Auto-calculated from check-in/out' },
            status: { type: 'string', enum: ['present', 'absent', 'late', 'half_day'] },
            notes: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Payroll: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            employeeId: { type: 'integer' },
            month: { type: 'integer', minimum: 1, maximum: 12 },
            year: { type: 'integer' },
            basicSalary: { type: 'number', format: 'decimal', readOnly: true, description: 'Auto-calculated from employee salary' },
            allowances: { type: 'number', format: 'decimal', readOnly: true, description: 'Auto-calculated (10% of basic salary)' },
            deductions: { type: 'number', format: 'decimal', readOnly: true, description: 'Auto-calculated (5% of basic salary)' },
            netSalary: { type: 'number', format: 'decimal', readOnly: true, description: 'Auto-calculated' },
            workingDays: { type: 'integer', readOnly: true, description: 'Auto-calculated from attendance' },
            status: { type: 'string', enum: ['pending', 'paid', 'cancelled'], readOnly: true, description: 'Defaults to pending' },
            paidDate: { type: 'string', format: 'date-time', nullable: true, readOnly: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        JobVacancy: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            title: { type: 'string' },
            departmentId: { type: 'integer' },
            description: { type: 'string', nullable: true },
            requirements: { type: 'string', nullable: true },
            salaryRange: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['open', 'closed', 'filled'] },
            postedDate: { type: 'string', format: 'date-time', readOnly: true },
            closingDate: { type: 'string', format: 'date-time', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Applicant: {
          type: 'object',
          properties: {
            id: { type: 'integer', readOnly: true, description: 'Auto-generated by system' },
            jobVacancyId: { type: 'integer' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string', nullable: true },
            resume: { type: 'string', nullable: true },
            coverLetter: { type: 'string', nullable: true },
            status: { type: 'string', enum: ['pending', 'shortlisted', 'rejected', 'hired'], readOnly: true, description: 'Defaults to pending' },
            appliedDate: { type: 'string', format: 'date-time', readOnly: true },
            interviewDate: { type: 'string', format: 'date-time', nullable: true },
            notes: { type: 'string', nullable: true },
            createdAt: { type: 'string', format: 'date-time', readOnly: true },
            updatedAt: { type: 'string', format: 'date-time', readOnly: true }
          }
        },
        Error: {
          type: 'object',
          properties: {
            error: { type: 'string' },
            message: { type: 'string' }
          }
        },
        LoginRequest: {
          type: 'object',
          required: ['email', 'password'],
          properties: {
            email: { type: 'string', format: 'email', example: 'employee@ingenzi.com' },
            password: { type: 'string', example: 'testpassword' }
          }
        },
        LoginResponse: {
          type: 'object',
          properties: {
            token: { type: 'string' },
            user: { $ref: '#/components/schemas/User' }
          }
        },
        CreateEmployeeRequest: {
          type: 'object',
          required: ['firstName', 'lastName', 'email', 'departmentId', 'position', 'salary', 'hireDate'],
          properties: {
            employeeId: { type: 'string', description: 'Optional - Auto-generated if not provided' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string' },
            departmentId: { type: 'integer' },
            position: { type: 'string' },
            salary: { type: 'number' },
            hireDate: { type: 'string', format: 'date' },
            address: { type: 'string' },
            status: { type: 'string', enum: ['active', 'inactive', 'terminated'], default: 'active' }
          },
          description: 'Note: id, createdAt, updatedAt are auto-generated by the system'
        },
        CreateDepartmentRequest: {
          type: 'object',
          required: ['name'],
          properties: {
            name: { type: 'string' },
            description: { type: 'string' },
            status: { type: 'string', enum: ['active', 'inactive'], default: 'active' }
          },
          description: 'Note: id, createdAt, updatedAt are auto-generated by the system'
        },
        CreateLeaveRequest: {
          type: 'object',
          required: ['leaveTypeId', 'startDate', 'endDate'],
          properties: {
            leaveTypeId: { type: 'integer' },
            startDate: { type: 'string', format: 'date' },
            endDate: { type: 'string', format: 'date' },
            reason: { type: 'string' }
          },
          description: 'Note: id, employeeId, days, status, appliedDate, createdAt, updatedAt are auto-generated/calculated by the system'
        },
        CreateAttendanceRequest: {
          type: 'object',
          required: ['employeeId', 'date', 'status'],
          properties: {
            employeeId: { type: 'integer' },
            date: { type: 'string', format: 'date' },
            checkIn: { type: 'string', format: 'date-time' },
            checkOut: { type: 'string', format: 'date-time' },
            status: { type: 'string', enum: ['present', 'absent', 'late', 'half_day'] },
            notes: { type: 'string' }
          },
          description: 'Note: id, hoursWorked, createdAt, updatedAt are auto-generated/calculated by the system'
        },
        GeneratePayrollRequest: {
          type: 'object',
          required: ['employeeId', 'month', 'year'],
          properties: {
            employeeId: { type: 'integer' },
            month: { type: 'integer', minimum: 1, maximum: 12 },
            year: { type: 'integer' }
          },
          description: 'Note: id, basicSalary, allowances, deductions, netSalary, workingDays, status, createdAt, updatedAt are auto-calculated/generated by the system'
        },
        CreateJobVacancyRequest: {
          type: 'object',
          required: ['title', 'departmentId'],
          properties: {
            title: { type: 'string' },
            departmentId: { type: 'integer' },
            description: { type: 'string' },
            requirements: { type: 'string' },
            salaryRange: { type: 'string' },
            closingDate: { type: 'string', format: 'date' },
            status: { type: 'string', enum: ['open', 'closed', 'filled'], default: 'open' }
          },
          description: 'Note: id, postedDate, createdAt, updatedAt are auto-generated by the system'
        },
        CreateApplicantRequest: {
          type: 'object',
          required: ['jobVacancyId', 'firstName', 'lastName', 'email'],
          properties: {
            jobVacancyId: { type: 'integer' },
            firstName: { type: 'string' },
            lastName: { type: 'string' },
            email: { type: 'string', format: 'email' },
            phone: { type: 'string' },
            resume: { type: 'string' },
            coverLetter: { type: 'string' }
          },
          description: 'Note: id, status (defaults to pending), appliedDate, createdAt, updatedAt are auto-generated by the system'
        }
      }
    },
    tags: [
      {
        name: 'Authentication',
        description: 'User authentication endpoints'
      },
      {
        name: 'Employees',
        description: 'Employee management endpoints'
      },
      {
        name: 'Departments',
        description: 'Department management endpoints'
      },
      {
        name: 'Leave',
        description: 'Leave management endpoints'
      },
      {
        name: 'Attendance',
        description: 'Attendance tracking endpoints'
      },
      {
        name: 'Payroll',
        description: 'Payroll management endpoints'
      },
      {
        name: 'Recruitment',
        description: 'Recruitment and job vacancy endpoints'
      },
      {
        name: 'Dashboard',
        description: 'Dashboard statistics and activity endpoints'
      }
    ]
  },
  apis: ['./routes/*.js', './server.js'] // Path to the API files
};

const swaggerSpec = swaggerJsdoc(options);

module.exports = swaggerSpec;

